apiVersion: v1
kind: Service
metadata:
  name: blog-frontend
  labels:
    app: blog-frontend
spec:
  type: NodePort
  selector:
    app: blog-frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
